女性限定イベント開催機能の追加
hayashi-toshihiro/mokumoku pull request #3
Opened 2023-05-31 07:50 UTC by hayashi-toshihiro

概要

女性限定のもくもく会の開催ができるように変更

変更理由

登録者が 男性：60%, 女性： 40% であるが、参加者のほとんど(90%)が男性であり、女性も参加できる環境とするため。

変更内容 
・性別の登録がセレクトボックスにて可能（その他、男性、女性　デフォルトは男性） 
・イベント作成時にuserが女性の時のみ、女性限定とするか否かのチェックボックスが表示される 
・イベント詳細にて、女性以外は女性限定イベントへの参加ボタンが表示されない
・イベント詳細、一覧にて女性限定イベントか否かを判別するためのテキストを表示する。

2023-06-01 04:59 UTC, Tsuchiya2 commented
ご提出ありがとうございます。
１つ前のレビューで共有されたRSpec実行した際の結果のスクリーンショットの共有もお願いできますでしょうか。
一旦差し戻し状態にしますので、RUNTEQアプリから再提出をお願いいたします。

2023-06-01 05:55 UTC, hayashi-toshihiro commented
失礼しました！
選択した事業課題と、RSpec実行時のスクリーンショットを追加し、再度RUNTEQアプリから提出しました。よろしくお願いします！！

2023-06-01 10:12 UTC, busitora requested changes
コメントしました！

2023-06-01 10:12 UTC, busitora commented on app/models/event.rb
> +  enum only_woman: { デフォルト: 0, 女性限定: 1 }
日本語ではなく英語にしましょうか!
すべての enum もあわせて修正してください

2023-06-01 10:12 UTC, busitora commented on app/views/events/_event.html.erb
> +      <% if event.only_woman == 1 %>
event.only_woman? としてください

2023-06-01 10:12 UTC, busitora commented on app/views/events/_form.html.erb
> +    <% if current_user.gender == 'woman' %>
上記同様、 current_user.woman? となるようにしてください。

基本、 == といった分岐処理が出た場合はモデルメソッド等に寄せると改修が楽になります。 同じような記述が増えたときのメンテナンスコストですね

2023-06-01 10:12 UTC, busitora commented on app/views/events/show.html.erb
> +          <% if @event.only_woman == 1 %>
上記同様

2023-06-01 10:12 UTC, busitora commented on app/views/events/show.html.erb
> +                  <% unless @event.only_woman == 1 && current_user.gender != 'woman' %>
上記同様

2023-06-01 10:12 UTC, busitora commented on app/views/users/new.html.erb
> +              <%= f.select :gender,[['other', :other],['男性', :man],['女性', :woman]], {}, class: 'form-select' %>
こちら、 男性、女性、 その他 をそのままいれるのではなく、 
例 User.roles_i18n.invert.map{|key, value| [key, User.roles[value]] のように、ベタ書きで対応するのは避けるべきですね

ここは難しければ今のままでいいですが、現場入った場合はおそらくできるまでLGTMはでないと思います！

2023-06-02 03:42 UTC, hayashi-toshihiro commented
再提出です！
コード外にも、コメントの仕方等わかりにくい点ありましたら、指摘していただけるとありがたいです！
よろしくお願いします！！

2023-06-02 12:08 UTC, takyyk commented
@hayashi-toshihiro 
LGTMです！

2023-06-02 23:14 UTC, merged